FROM node:20 as builder

COPY .env .

WORKDIR /src

COPY package*.json .

RUN npm install

COPY src/ src/

FROM node:20 as runner

WORKDIR /app

COPY --from=builder src/package*.json .
COPY --from=builder src/node_modules node_modules

CMD ["npm", "start"]